#!/bin/sh

# ask if user wants to use sudo or doas
echo "sudo or doas (s/d)" && read i

# if the user enters "d" run this command 
if [ "$i" = "d" ]; then 
	git clone https://github.com/hexisXz/openg.git && cd ./openg && doas mv openg /usr/local/bin/ 
fi

# if the user enters "s" run this command
if [ "$i" = "s" ]; then
	git clone https://github.com/hexisXz/openg.git && cd ./openg && sudo mv openg /usr/local/bin/ 
fi

