#!/bin/sh

# ask if user wants to use sudo or doas
echo "sudo or doas (s/d)" && read i

# if the user enters "d" run this command 
[ "$i" == "d" ] && cd ./openg && doas mv openg /usr/local/bin/ 

# if the user enters "s" run this command
[ "$i" == "s" ] && cd ./openg && sudo mv openg /usr/local/bin/ 

